<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0</TargetFrameworks>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>..\SafeRouting.snk</AssemblyOriginatorKeyFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <LangVersion>10.0</LangVersion>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'netstandard2.0'">
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' != 'netstandard2.0'">
    <AdditionalFiles Include="PublicAPI.net\PublicAPI.Shipped.txt" />
    <AdditionalFiles Include="PublicAPI.net\PublicAPI.Unshipped.txt" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework)' == 'netstandard2.0'">
    <AdditionalFiles Include="PublicAPI.netstandard\PublicAPI.Shipped.txt" />
    <AdditionalFiles Include="PublicAPI.netstandard\PublicAPI.Unshipped.txt" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="PublicAPI.netstandard\" />
  </ItemGroup>

</Project>
