name: Publish

on:
  workflow_dispatch:
  release:
    types:
    - published

env:
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v4

    - name: Setup .Net
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.1.1
      with:
        versionSpec: '5.x'
    - name: Use GitVersion
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v3.1.1
    - run: |
        echo "NuGetVersionV2: ${{ steps.gitversion.outputs.nuGetVersionV2 }}"
        echo "NuGetPreReleaseTagV2 (not used): ${{ steps.gitversion.outputs.CommitsSinceVersionSourcePadded }}"

    - name: Restore dependencies
      run: dotnet restore --nologo

    - name: Pack
      run: dotnet pack --nologo --no-restore ./SafeRouting.Generator -c Release -o ./artifacts /p:ContinuousIntegrationBuild=true -p:Version=${{ steps.gitversion.outputs.MajorMinorPatch }}

    - name: Build integration tests
      run: dotnet build Test/SafeRouting.Tests.Integration -c Release -p:SafeRoutingPackageVersion=${{ steps.gitversion.outputs.MajorMinorPatch }}

    - name: Run integration tests
      run: dotnet test Test/SafeRouting.Tests.Integration -c Release --no-build --no-restore

    - name: Push to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg -k ${{ secrets.NUGET_APIKEY }} -s ${{ env.NUGET_SOURCE_URL }}

